import mongoose, { Schema } from "mongoose";
import jwt from "jsonwebtoken";
import bcrypt from "bcrypt";

const userSchema = new Schema(
  {
    username: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
      index: true, //better approuch for searching
    },
    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
    },
    fullname: {
      type: String,
      required: true,

      lowercase: true,
      trim: true,
      index: true, //better approuch for searching
    },
    avatar: {
      type: String,
      required: true,
    },

    coverimage: {
      type: String,
    },
    watchHistory: [
      {
        type: Schema.Types.ObjectId,
        ref: "Video",
      },
    ],
    password: {
      type: String,
      required: true,
    },
    refreshToken: {
      type: String,
    },
  },
  {
    timestamps: true,
  }
);


userSchema.pre("save", async function (next) {
  if (!this.isModified("password")) return next();
  this.password = bcrypt.hash(this.password, 10);
  next();
});

userSchema.methods.isPasswordCorrect = async function (password) {
  return await bcrypt.compare(password, this.password);
};

//use of jwt

//access token is for short term , after some time its gonna expire
userSchema.methods.generateAccessToken = function () {
  return jwt.sign(
    {
      _id: this._id,
      email: this.email,
      username: this.username,
      fullname: this.fullname,
    },
    sdkfhdkshgsdkghsdkfghkjsfhgkshghskj, //secret key
    {
      expiresIn: 10,
    }
  );
};

// refresh token is for long term , if user have this token, new refresh token can be generated by refresh token
userSchema.methods.generateRefreshToken = function () {
  return jwt.sign(
    {
      _id: this._id,
    },
    sdkfhdkshglskdfjlskdfsdkghsdkfghkjsfhgkshghskj,
    {
      expiresIn: 100,
    }
  );
};

export const User = mongoose.model("user", userSchema);
